import { Material, Ply } from '@/types/materials';
import { GeometryConfig } from '@/types/geometry';

interface FEAExportOptions {
  plies: Ply[];
  materials: Record<string, Material>;
  geometry: GeometryConfig;
  format: 'inp' | 'cdb';
}

export function generateAbaqusINP(options: FEAExportOptions): string {
  const { plies, materials, geometry } = options;
  
  let inp = '*HEADING\n';
  inp += 'Composite Laminate Analysis Export\n';
  inp += 'Generated by Composite Material Calculator\n';
  inp += '**\n';
  
  // Material definitions
  inp += '** MATERIALS\n';
  const uniqueMaterials = new Set(plies.map(p => p.material));
  
  uniqueMaterials.forEach((matName, idx) => {
    const mat = materials[matName];
    if (!mat) return;
    
    inp += `*MATERIAL, NAME=${matName.replace(/\s+/g, '_')}\n`;
    inp += '*ELASTIC, TYPE=ENGINEERING CONSTANTS\n';
    inp += `${mat.E1}, ${mat.E2}, ${mat.E2}, ${mat.nu12}, ${mat.nu12}, ${mat.nu12}, ${mat.G12}, ${mat.G12}\n`;
    inp += `${mat.G12}\n`;
    
    if (mat.tensile_strength || mat.compressive_strength || mat.shear_strength) {
      inp += '*FAIL STRESS\n';
      inp += `${mat.tensile_strength || 0}, ${mat.compressive_strength || 0}, ${mat.tensile_strength || 0}, ${mat.compressive_strength || 0}, ${mat.shear_strength || 0}, ${mat.shear_strength || 0}\n`;
    }
    inp += '**\n';
  });
  
  // Shell section with composite layup
  inp += '** SHELL SECTION\n';
  inp += '*SHELL SECTION, ELSET=Laminate, COMPOSITE\n';
  
  plies.forEach((ply, idx) => {
    const mat = materials[ply.material];
    if (!mat) return;
    const matName = ply.material.replace(/\s+/g, '_');
    inp += `${mat.thickness}, 3, ${matName}, ${ply.angle}, Ply_${idx + 1}\n`;
  });
  
  inp += '**\n';
  inp += '** GEOMETRY\n';
  if (geometry.type === 'plate') {
    inp += `** Plate geometry\n`;
  } else {
    inp += `** Tube geometry: OD=${geometry.outerDiameter}mm, ID=${geometry.innerDiameter}mm\n`;
  }
  inp += '**\n';
  inp += '** End of export\n';
  
  return inp;
}

export function generateANSYSCDB(options: FEAExportOptions): string {
  const { plies, materials, geometry } = options;
  
  let cdb = '/PREP7\n';
  cdb += '! Composite Laminate Analysis Export\n';
  cdb += '! Generated by Composite Material Calculator\n';
  cdb += '!\n';
  
  // Material definitions
  cdb += '! MATERIALS\n';
  const uniqueMaterials = new Set(plies.map(p => p.material));
  
  uniqueMaterials.forEach((matName, idx) => {
    const mat = materials[matName];
    if (!mat) return;
    
    const matNum = idx + 1;
    cdb += `MP,EX,${matNum},${mat.E1}\n`;
    cdb += `MP,EY,${matNum},${mat.E2}\n`;
    cdb += `MP,EZ,${matNum},${mat.E2}\n`;
    cdb += `MP,PRXY,${matNum},${mat.nu12}\n`;
    cdb += `MP,PRYZ,${matNum},${mat.nu12}\n`;
    cdb += `MP,PRXZ,${matNum},${mat.nu12}\n`;
    cdb += `MP,GXY,${matNum},${mat.G12}\n`;
    cdb += `MP,GYZ,${matNum},${mat.G12}\n`;
    cdb += `MP,GXZ,${matNum},${mat.G12}\n`;
    
    if (mat.tensile_strength || mat.compressive_strength || mat.shear_strength) {
      cdb += `TB,FCLI,${matNum},,,TWFC\n`;
      cdb += `TBDATA,1,${mat.tensile_strength || 0},${mat.compressive_strength || 0},${mat.tensile_strength || 0},${mat.compressive_strength || 0},${mat.shear_strength || 0},${mat.shear_strength || 0}\n`;
    }
    cdb += `! Material: ${matName}\n`;
  });
  
  cdb += '!\n';
  cdb += '! SECTION DEFINITION\n';
  cdb += 'SECTYPE,1,SHELL\n';
  cdb += `SECDATA,${plies.reduce((sum, p) => sum + (materials[p.material]?.thickness || 0), 0)},1,0,3\n`;
  
  plies.forEach((ply, idx) => {
    const mat = materials[ply.material];
    if (!mat) return;
    const matNum = Array.from(uniqueMaterials).indexOf(ply.material) + 1;
    cdb += `SECDATA,${mat.thickness},${matNum},${ply.angle},3\n`;
  });
  
  cdb += '!\n';
  cdb += '! GEOMETRY\n';
  if (geometry.type === 'plate') {
    cdb += `! Plate geometry\n`;
  } else {
    cdb += `! Tube geometry: OD=${geometry.outerDiameter}mm, ID=${geometry.innerDiameter}mm\n`;
  }
  
  cdb += '!\n';
  cdb += 'FINISH\n';
  cdb += '! End of export\n';
  
  return cdb;
}

export function downloadFEAFile(content: string, filename: string) {
  const blob = new Blob([content], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
